### ISSUE TITLE
训练资源情况

### ISSUE THREAD

**Issue by ScottishFold007** [LowinLi/chinese-bigbird#1]
楼主，你好！你这个项目很棒，填补了国内空白！想请教下，你这个训练数据多少MB，是什么样的训练资源？花了多久？谢谢哈！

**Comment by LowinLi** [comment]
您好，谢谢您关注我这个项目，现在开源的tiny版本，是用的clue项目开源的预训练语料，从中间抽出超过512个词的句子。抽出的语料大概占用硬盘8个g，梯度累计训练，两块1080显卡，跑了一个月，150k个step

**Comment by xxllp** [comment]
这么秀吗 两个1080ti

**Comment by LowinLi** [comment]
> 这么秀吗 两个1080ti

穷呗，只能慢慢梯度累计更新参数
