### ISSUE TITLE
bigbert如何微调

### ISSUE THREAD

**Issue by csxrzhang** [LowinLi/chinese-bigbird#2]
如何微调？感谢楼主

**Comment by LowinLi** [comment]
> 如何微调？感谢楼主

其实介绍用transformers做微调的帖子已经有很多了，例如：
https://zhuanlan.zhihu.com/p/202615056
https://zhuanlan.zhihu.com/p/111733365

当然最好是参考官网文档
https://huggingface.co/transformers/training.html

如何用我这里的模型，就是把这些介绍里面的
```
BertModelForSequenceClassification.from_pretrained("bert-base-cased")
```
换成
```
model = BigBirdForSequenceClassification.from_pretrained('Lowin/chinese-bigbird-tiny')
tokenizer = JiebaTokenizer.from_pretrained('Lowin/chinese-bigbird-tiny')
```
