### ISSUE TITLE
Is maximum length == 1024?

### ISSUE THREAD

**Issue by mzhadigerov** [LowinLi/chinese-bigbird#3]
Hi!

I'm using `https://huggingface.co/transformers/training.html`  to fine tune your model.

At `trainer.train()` step I'm getting error that input size should be 1024. 

After I changed: 

```
def tokenize_function(examples):
    return tokenizer(examples["text_a"], padding="max_length", truncation=True, max_length=4096)

tokenized_datasets = dataset_dict.map(tokenize_function, batched=True)
```

to

```
def tokenize_function(examples):
    return tokenizer(examples["text_a"], padding="max_length", truncation=True, max_length=1024)

tokenized_datasets = dataset_dict.map(tokenize_function, batched=True)
```

It worked

**Comment by LowinLi** [comment]
Sorry

I pretrained the chinese-bigbird-tiny and chinese-bigbird-small with max_length 1024。

https://github.com/LowinLi/chinese-bigbird#%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83%E5%8F%82%E6%95%B0

So the parameter of max_length can not be set out of 1024.

Moreover the shape of model position_embeddings is just 1024, it can not work with sequence length exceed 1024.

I am pretraining chinese-bigbird-base with block 4096 and  release it at next month.

Thanks for your attention:)

**Comment by LowinLi** [comment]
> Hi!
> 
> I'm using `https://huggingface.co/transformers/training.html` to fine tune your model.
> 
> At `trainer.train()` step I'm getting error that input size should be 1024.
> 
> After I changed:
> 
> ```
> def tokenize_function(examples):
>     return tokenizer(examples["text_a"], padding="max_length", truncation=True, max_length=4096)
> 
> tokenized_datasets = dataset_dict.map(tokenize_function, batched=True)
> ```
> 
> to
> 
> ```
> def tokenize_function(examples):
>     return tokenizer(examples["text_a"], padding="max_length", truncation=True, max_length=1024)
> 
> tokenized_datasets = dataset_dict.map(tokenize_function, batched=True)
> ```
> 
> It worked

hello, I have release chinese-bigbird-base-4096 and chinese-bigbird-wwm-base-4096 for maximum length == 4096

Thanks for your star

**Comment by mzhadigerov** [comment]
Oh! Great job! Thank you for your effort 👍👍👍
