### ISSUE TITLE
模型效果

### ISSUE THREAD

**Issue by xxllp** [LowinLi/chinese-bigbird#5]
看你readme 里面的模型 换成bigbird 效果还没有512的长度好 ，这个是正常的？

**Comment by LowinLi** [comment]
您说的是chinese-bigbird-wwm-base-4096相比chinese-roberta-wwm-ext吧。
这是有可能的，因为bigbird并不是全注意力机制，有很多block在单层之间是没有连接的。

我没有找到中文很长的公开分类数据集，就只能找到700多长度的iflytek公开数据，所以实际上4096长度的bigbird跟512的模型比，并没有体现出太多优势。

我放在readme的初衷只是用来体现，这些bigbird没有比chinese-roberta-wwm-ext指标下降太多，毕竟[chinese-roberta-wwm-ext](https://github.com/ymcui/Chinese-BERT-wwm)可是开源的同参数量，几乎最牛的预训练模型了。

**Comment by xxllp** [comment]
原来如此 我本地有长度几千的文本 回头试试看

**Comment by LowinLi** [comment]
> 原来如此 我本地有长度几千的文本 回头试试看

好嘞，如果方便，劳驾来个星😂

**Comment by xxllp** [comment]
我举得做分类差别可能不如摘要来的明显
