### ISSUE TITLE
wwm的分词预处理逻辑能补充下吗？

### ISSUE THREAD

**Issue by jinxinglu** [LowinLi/chinese-bigbird#6]
hfl的roberta用的是LTC分词，楼主用的分词预处理逻辑可以补充下吗？

**Comment by LowinLi** [comment]
我直接用jieba做的，没有用LTC，使用的[huggingface里的脚本](https://github.com/huggingface/transformers/blob/master/examples/pytorch/language-modeling/run_mlm_no_trainer.py)改的

**Comment by LowinLi** [comment]
> hfl的roberta用的是LTC分词，楼主用的分词预处理逻辑可以补充下吗？

https://github.com/LowinLi/chinese-bigbird/tree/main/src/wwm_pretrain

**Comment by LowinLi** [comment]
> hfl的roberta用的是LTC分词，楼主用的分词预处理逻辑可以补充下吗？

https://github.com/LowinLi/chinese-bigbird/tree/main/src/wwm_pretrain
我补充了一下之前的jieba wwm预训练代码，写的不好，仅供参考

**Comment by jinxinglu** [comment]
参考一下，谢谢楼主

**Comment by LowinLi** [comment]
https://github.com/LowinLi/chinese-bigbird#wwm%E9%A2%84%E8%AE%AD%E7%BB%83%E6%B5%81%E7%A8%8B

wwm流程也补充了一下哦
